build/ps-entrypoint.sh, deploy/cr.yaml, pkg/cluster/replication.go, pkg/database/mysql/replicator.go, pkg/k8s/secrets.go
Orchestrator 3.2.6 has a new feature to enforce exact number of
semi-sync nodes. According to `rpl_semi_sync_master_wait_for_slave_count`
variable it enable/disable semi-sync replication on replica nodes.
If the user configures `sizeSemiSync` in `cr.yaml`, the operator enables semi-sync
replication on the primary (`set global rpl_semi_sync_master_enabled=1`)
and set `rpl_semi_sync_master_wait_for_slave_count` to the user defined
value. Afterwards, Orchestrator will detect a failure due to
`EnforceExactSemiSyncReplicas` config option of itself and will try to
configure replicas as semi-sync to reach to the desired state.
If the user sets `sizeSemiSync` to 0 or removes the field, the operator
disables the semi-sync on primary (`set global rpl_semi_sync_master_enabled=0`).
Orchestrator won't …
=> K8SPS-18: Configure semi-sync nodes through orchestrator

build/ps-entrypoint.sh, cmd/bootstrap/main.go, pkg/cluster/mysql.go, pkg/database/mysql/env.go, pkg/database/mysql/replicator.go, pkg/database/mysql/service.go
* in mysql-monit container we need to use service for
peer-list to get ready pods but by default
<cluster-name>-mysql service has 'publishNotReadyAddresses=True'
so, the additional service <cluster-name>-mysql-unready was
created
* addopt bootstrap to use <cluster-name>-mysql-unready service
=> K8SPS-13 improve orchestrator discovery MySQL pods

api/v2/perconaserverformysql_types.go, build/ps-entrypoint.sh, controllers/perconaserverformysql_controller.go, e2e-tests/tests/sidecars/01-assert.yaml, pkg/k8s/configmap.go, pkg/k8s/utils.go, pkg/mysql/mysql.go
We support three different ways to customize MySQL configuration:
1. `spec.mysql.configuration` field in `cr.yaml`. In this case, the operator will
create the ConfigMap.
2. Creating a ConfigMap named `<cluster-name>-mysql` that contains the key `my.cnf`
3. Creating a Secret named `<cluster-name>-mysql` that contains the key `my.cnf`
We project ConfigMap and Secret in the same volume. In the entrypoint we
concat these files into MySQL config file (`/etc/my.cnf.d/node.cnf`). By
projecting these two resources, users will be able to split their
customizations. Sensitive values can live in the Secrets while the rest
live in the ConfigMap.
To automatically restart the MySQL pods on configuration change, we
calculate the md5 hash from the value of the `spec.mysql.configuration`
and store it in …
=> K8SPS-28: Allow custom config for MySQL

api/v2/perconaserverformysql_types.go, build/ps-entrypoint.sh, controllers/perconaserverformysql_controller.go, go.mod, go.sum, pkg/k8s/secrets.go, pkg/k8s/utils.go, pkg/mysql/mysql.go, pkg/orchestrator/client.go, pkg/orchestrator/orchestrator.go, pkg/replicator/replicator.go, pkg/secret/secret.go, pkg/users/users.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/modules.txt
We're depending on internal users secret for this feature as in PXC
operator. After user updates the secret object that referenced in
`cr.Spec.SecretsName`, the operator connects to MySQL **primary** and
runs `ALTER USER`. The connection is created using the old password in
the internal secret. If `ALTER USER` succeeds for all updated user
passwords, the internal secret object is updated with new values.
We have special cases for some users:
1. `monitor` user: If PMM is enabled, the operator restarts the MySQL
pods.
2. `orchestrator` user: The operator restarts the Orchestrator pods.
3. `replication` user: The operator stops replication on each replica,
updates the password, change replication password for the default
channel and starts replication. The operator sends HTTP requests to …
=> K8SPS-35: System users management

deploy/cr.yaml
Except for the custom config example I have move the sidecars example 1 space to the right so that if you just remove `#` with sed or something it will work (I think it's the same in PXC examples)
=> Add example for custom configuration

e2e-tests/functions, e2e-tests/tests/config/01-assert.yaml, e2e-tests/tests/config/02-assert.yaml, e2e-tests/tests/config/04-assert.yaml, e2e-tests/tests/config/06-assert.yaml, e2e-tests/tests/init-deploy/01-assert.yaml, e2e-tests/tests/semi-sync/01-assert.yaml, e2e-tests/tests/service-per-pod/01-assert.yaml, e2e-tests/tests/service-per-pod/03-read-from-clusterip.yaml, e2e-tests/tests/service-per-pod/04-assert.yaml, e2e-tests/tests/service-per-pod/05-read-from-loadbalancer.yaml, e2e-tests/tests/users/04-check-cluster.yaml
TEST RESULTS:
GKE: https://cloud.cd.percona.com/view/PSO/job/ps-operator-gke-version/41/
EKS: https://cloud.cd.percona.com/view/PSO/job/ps-operator-eks/36/
OpenShift: https://cloud.cd.percona.com/view/PSO/job/ps-operator-aws-openshift-4/31/
=> K8SPS-66 - fix service-per-pod test and timeouts for OpenShift

api/v1alpha1/perconaservermysql_types.go, build/ps-entrypoint.sh, cmd/healthcheck/main.go, config/crd/bases/ps.percona.com_perconaservermysqls.yaml, controllers/perconaservermysql_controller.go, deploy/bundle.yaml, deploy/crd.yaml, e2e-tests/functions, e2e-tests/tests/service-per-pod/01-create-cluster-clusterip.yaml, e2e-tests/tests/service-per-pod/04-create-cluster-loadbalancer.yaml, pkg/mysql/mysql.go, pkg/orchestrator/orchestrator.go, pkg/users/users.go
If the user changes spec.secretsName and the new secret object contains
updated passwords, MySQL probes start to fail and cluster crashes. We
were mounting the secret referenced in spec.secretsName, with this
commit we mount the internal secret to MySQL and Orchestrator pods.
Also, we're now using the dual password feature that introduced in MySQL 8.
We update the user passwords with `RETAIN CURRENT PASSWORD` and discard
the old passwords after the cluster becomes stable after restarts.
=> K8SPS-70: Fix changing CR secret name with new passwords

build/ps-entrypoint.sh
We're adding super_read_only to the MySQL config after initialization
completed because it interferes with initialization procedure.
=> K8SPS-41: Use super_read_only

e2e-tests/vars.sh
Hi,
there is no description how to build the operator and have CRs visible in K8s (minikube). 
I tried to do some tweaks and output is successful
<details> <summary> Before patch </summary> 
<pre>
$ make
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen crd rbac:roleName=percona-server-mysql-operator webhook paths="./..." output:crd:artifacts:config=config/crd/bases  ## Generate WebhookConfiguration, Role and CustomResourceDefinition objects.
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen object:headerFile="LICENSE-HEADER" paths="./..." ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
ROOT_REPO=/home/anel/percona/percona-server-mysql-operator VERSION=anel-try-to-build …
=> Build custom resource locally 

cmd/sidecar/main.go, deploy/cr.yaml
* add '--target-dir' option for xtrabackup to avoid the
following error 'cannot mkdir: 13 /xtrabackup_backupfiles/'
in case xtrabackup is not running under the root
=> K8SPS-104 add '--target-dir' option for xtrabackup

e2e-tests/build
This fixes default build on M1 Mac for example.
=> Set DOCKER_DEFAULT_PLATFORM to linux/amd64 in the build script

deploy/cr.yaml
Added a commented out `prefix` field to cr.yaml.  In our CR we have only S3 as an example, maybe we can add examples for other storages, Azure and GCS.
=> Add commented out prefix field to CR.

Jenkinsfile, deploy/cr.yaml
[![K8SPS-152](https://badgen.net/badge/JIRA/K8SPS-152/green)](https://jira.percona.com/browse/K8SPS-152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
ClusterIP is used by default, but option is needed if you want to set it to LoadBalancer
=> K8SPS-152 - Add expose option for orchestrator in cr.yaml

pkg/mysql/mysql.go
[![K8SPS-17](https://badgen.net/badge/JIRA/K8SPS-17/green)](https://jira.percona.com/browse/K8SPS-17) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-17
=> K8SPS-17: use `pt-heartbeat` only with async clusterType

controllers/perconaservermysql_controller.go
[![K8SPS-63](https://badgen.net/badge/JIRA/K8SPS-63/green)](https://jira.percona.com/browse/K8SPS-63) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Like we have it in PXC, if we fail to get versions from VS, we should continue with default ones. 
Here is the logic in PXC: https://github.com/percona/percona-xtradb-cluster-operator/blob/main/pkg/controller/pxc/controller.go#L304
=> K8SPS-63: Using default version when failing to get them from VS

build/Dockerfile, controllers/perconaservermysql_controller.go, pkg/mysqlsh/mysqlsh.go
In MySQL Shell 8.0.30 `communicationStack` option was added. By default, it uses the `MYSQL` communication stack value, which doesn't allow us to use the `ipAllowList` option.
As mentioned here: https://dev.mysql.com/doc/relnotes/mysql-shell/8.0/en/news-8-0-30.html, the `MYSQL` communication stack obsoletes the usage of IP allowlists. So, they should be removed.
Also, fixes the `mysqlsh` warning `Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory` by installing `glibc-langpack-en`
=> Fix group-replication cluster creation

controllers/perconaservermysqlbackup_controller.go
[![K8SPS-175](https://badgen.net/badge/JIRA/K8SPS-175/green)](https://jira.percona.com/browse/K8SPS-175) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-175
This PR changes the backup destination provided to `xbcloud` in the `delete-backup` finalizer. Previously we provided destination from backup status with `gs://`- like prefixes and bucket/container names. We should strip prefixes and bucket/container names because:
1. `xbcloud` doesn't support the `gs://` prefix: https://github.com/percona/percona-xtrabackup/blob/a19fe35f768256a81cad3f2f421f9049b …
=> K8SPS-175: fix `delete-backup` finalizer

deploy/cr.yaml, e2e-tests/functions, pkg/mysql/config.go
[![K8SPS-181](https://badgen.net/badge/JIRA/K8SPS-181/green)](https://jira.percona.com/browse/K8SPS-181) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* 75% of RAM it is big value for innodb_buffer_pool_size
in order to avoid OOMKilled we need to use max 50%    
* set group-replication as a default type in CR
=> K8SPS-181 decrease the value for innodb_buffer_pool_size option

Jenkinsfile, e2e-tests/kuttl.yaml, e2e-tests/tests/auto-config/12-drop-finalizer, e2e-tests/tests/config/09-drop-finalizer, e2e-tests/tests/demand-backup/23-drop-finalizer, e2e-tests/tests/gr-demand-backup/19-drop-finalizer, e2e-tests/tests/gr-init-deploy/06-drop-finalizer, e2e-tests/tests/haproxy/10-drop-finalizer, e2e-tests/tests/init-deploy/06-drop-finalizer, e2e-tests/tests/limits/08-drop-finalizer, e2e-tests/tests/monitoring/04-drop-finalizer, e2e-tests/tests/one-pod/07-drop-finalizer, e2e-tests/tests/scaling/09-drop-finalizer, e2e-tests/tests/semi-sync/05-drop-finalizer, e2e-tests/tests/service-per-pod/06-drop-finalizer, e2e-tests/tests/sidecars/02-drop-finalizer, e2e-tests/tests/tls-cert-manager/03-drop-finalizer, e2e-tests/tests/users/05-drop-finalizer, e2e-tests/tests/version-service/08-drop-finalizer
[![K8SPS-78](https://badgen.net/badge/JIRA/K8SPS-78/green)](https://jira.percona.com/browse/K8SPS-78) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The latest version of kuttls waits for namespace removal. In our case would have waited forever of fail on timeout since the finalizer restricts k8s from cluster object removal. Additing finalizers wipeout then.
A few words about timeout on TestSuite level. The default timeout for namespace deletion in not long enough for us. Since it's not managed by any TestStep this is the only way how we can ask kuttl to wait a bit longer.
=> K8SPS-78 Kuttl 0.15.0 compatibility update

Jenkinsfile
[![CLOUD-765](https://badgen.net/badge/JIRA/CLOUD-765/green)](https://jira.percona.com/browse/CLOUD-765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We print version from github repo and not the version which is installed (it can be different).*
**Solution:**
*Just install the kuttl and print installed version.*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-765 - Fix printing of installed kuttl version

Jenkinsfile
[![CLOUD-769](https://badgen.net/badge/JIRA/CLOUD-769/green)](https://jira.percona.com/browse/CLOUD-769) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-769 Freeze kuttl version during release cycle

api/v1alpha1/perconaservermysql_types.go, cmd/manager/main.go, cmd/orc-handler/main.go, controllers/perconaservermysql_controller.go, controllers/perconaservermysqlbackup_controller.go, controllers/perconaservermysqlrestore_controller.go, pkg/mysqlsh/mysqlsh.go
[![K8SPS-236](https://badgen.net/badge/JIRA/K8SPS-236/green)](https://jira.percona.com/browse/K8SPS-236) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
In a couple of places, we use formatted log messages, breaking the whole structured logging thing we have.
**Cause:**
Misuse of our logging lib.
**Solution:**
Replace formatted messages with constant messages and proper use of KV pairs for the dynamic part of a log.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-236: Remove formatted strings from log messages.

cmd/manager/main.go, pkg/controller/ps/controller.go, pkg/controller/psbackup/controller.go, pkg/controller/psrestore/controller.go, pkg/controller/suite_test.go
[![K8SPS-242](https://badgen.net/badge/JIRA/K8SPS-242/green)](https://jira.percona.com/browse/K8SPS-242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Problem:**
Having all the controllers in a single package we don't have a clean separation of concerns and it is harder to test.
**Solution:**
Reorganize controllers from
```
controllers
perconaservermysql_controller.go
perconaservermysqlbackup_controller.go
perconaservermysqlrestore_controller.go
```
to
```
pkg
controller
ps
controller.go
psbackup
controller.go
psrestore
controller.go
```
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPS-242: Refactor - Reorganize controllers

Jenkinsfile
[![CLOUD-775](https://badgen.net/badge/JIRA/CLOUD-775/green)](https://jira.percona.com/browse/CLOUD-775) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Currently in dev pipelines when a new commit is pushed we delete the associated kubernetes clusters for the previous build, but if the pipeline was in its parallel stage in that case the jenkins executor might get stuck so the executor spot instance will be killed only later.*
**Solution:**
*In the clusterRunner() and in runTest() when the test needs to be re-run on next test run check if there …
=> CLOUD-775 - Fix cancelation of parallel pipeline build

pkg/controller/ps/controller.go, pkg/controller/ps/tls_test.go
[![K8SPS-168](https://badgen.net/badge/JIRA/K8SPS-168/green)](https://jira.percona.com/browse/K8SPS-168) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When the wrong `spec.tls.issuerConf` is specified, we don't provide a clear error message.
**Solution:**
Besides having a more clear error message, when we get issuerConf from the user, first check if the issuer is created and ready before proceeding.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-168: Check if the specified CM issuer exist

pkg/controller/ps/controller_test.go, pkg/controller/ps/tls_test.go
[![K8SPS-253](https://badgen.net/badge/JIRA/K8SPS-253/green)](https://jira.percona.com/browse/K8SPS-253) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Flaky delete-ssl finalizer integration tests.
**Cause**
"Simulating cert-manager" in `delete-ssl` finalizer test. The goroutine that is spun and the necessary `time.sleep` simply introduces non-determinism into the test suite.
**Solution**
Remove the case that needs "simulating cert-manager". This case simply requires that is covered with e2e test since running cert-manager operator is needed. …
=>  K8SPS-253: Fix flaky integration tests

Jenkinsfile
[![CLOUD-783](https://badgen.net/badge/JIRA/CLOUD-783/green)](https://jira.percona.com/browse/CLOUD-783) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Services which use LoadBalancer can leave external objects in GKE when the cluster is deleted.*
**Solution:**
*We delete operator/services and some other objects prior to cluster deletion so external LoadBalancers and related objects should get cleaned up.*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-783 - Cleanup test cluster before deletion

api/v1alpha1/perconaservermysql_types.go, build/ps-entrypoint.sh, cmd/bootstrap/async_replication.go, cmd/bootstrap/group_replication.go, cmd/bootstrap/main.go, cmd/bootstrap/utils.go, cmd/healthcheck/main.go, cmd/manager/main.go, config/crd/bases/ps.percona.com_perconaservermysqls.yaml, config/rbac/role.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/rbac.yaml, e2e-tests/tests/limits/01-assert.yaml, e2e-tests/tests/limits/03-assert.yaml, e2e-tests/tests/limits/05-assert.yaml, pkg/controller/ps/controller.go, pkg/controller/ps/crash_recovery.go, pkg/controller/ps/suite_test.go, pkg/mysql/topology/topology.go, pkg/mysqlsh/mysqlshexec.go, pkg/replicator/replicator.go, pkg/replicator/replicatorexec.go
[![K8SPS-280](https://badgen.net/badge/JIRA/K8SPS-280/green)](https://jira.percona.com/browse/K8SPS-280) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Before these changes, we were rebooting the cluster from complete outage from pod-0, without checking which member has the latest transactions. Therefore our full cluster recovery implementation was prone to data loss.
Now we're using mysql-shell's built-in checks to detect the member to reboot from. For this, mysql-shell requires every member to be reachable, so it can connect and check GTID's in each one. That means in case of full …
=> K8SPS-280: Improve full cluster crash recovery

e2e-tests/functions
[![CLOUD-789](https://badgen.net/badge/JIRA/CLOUD-789/green)](https://jira.percona.com/browse/CLOUD-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
*This just fixes the command to work on older bash versions since we don't use `/usr/bin/env bash` but specifically specify `/bin/bash`*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-789 - Fix check_passwords_leak function in tests for older bash versions

pkg/replicator/replicatorexec.go
[![K8SPS-276](https://badgen.net/badge/JIRA/K8SPS-276/green)](https://jira.percona.com/browse/K8SPS-276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Seems they are orphaned functions since semi sync replication is removed completely.*
**Solution:**
*Remove*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-276 - Remove SetSemiSyncSize and SetSemiSyncSource functions

e2e-tests/functions
[![CLOUD-789](https://badgen.net/badge/JIRA/CLOUD-789/green)](https://jira.percona.com/browse/CLOUD-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We were ignoring pmm client container, but for PS operator leaked monitor user password should be fixed under K8SPS-272*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-789 - Don't ignore pmm-client for password leaks check

api/v1alpha1/perconaservermysql_types.go, api/v1alpha1/perconaservermysqlbackup_types.go, api/v1alpha1/perconaservermysqlrestore_types.go
[![K8SPS-290](https://badgen.net/badge/JIRA/K8SPS-290/green)](https://jira.percona.com/browse/K8SPS-290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
I noticed that many functions were lacking the comments.
**Cause:**
**Solution:**
So I decided to give comments to two files functions and I also want to know if you give me permission to add other comments also.
Thank you!
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-290: Added comments above the two files functions

api/v1alpha1/perconaservermysql_types.go, pkg/controller/ps/status.go
[![K8SPS-292](https://badgen.net/badge/JIRA/K8SPS-292/green)](https://jira.percona.com/browse/K8SPS-292) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
CR status is initializing if cluster is paused. It should be `stopping` while pods are terminating and `paused` when cluster is paused.
**Cause:**
Not implemented.
**Solution:**
Implement.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-292: Fix CR status if cluster is paused

e2e-tests/run-distro.csv, e2e-tests/run-minikube.csv, e2e-tests/run-pr.csv, e2e-tests/run-release.csv, e2e-tests/tests/gr-demand-backup-haproxy/00-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/00-minio-secret.yaml, e2e-tests/tests/gr-demand-backup-haproxy/01-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/01-deploy-operator.yaml, e2e-tests/tests/gr-demand-backup-haproxy/02-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/02-create-cluster.yaml, e2e-tests/tests/gr-demand-backup-haproxy/03-write-data.yaml, e2e-tests/tests/gr-demand-backup-haproxy/04-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/04-create-backup-minio.yaml, e2e-tests/tests/gr-demand-backup-haproxy/05-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/05-delete-data.yaml, e2e-tests/tests/gr-demand-backup-haproxy/06-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/06-restore-from-minio.yaml, e2e-tests/tests/gr-demand-backup-haproxy/07-assert.yaml, e2e-tests/tests/gr-demand-backup-haproxy/07-read-data.yaml, e2e-tests/tests/gr-demand-backup-haproxy/08-drop-finalizer.yaml, pkg/controller/psrestore/controller.go
[![K8SPS-305](https://badgen.net/badge/JIRA/K8SPS-305/green)](https://jira.percona.com/browse/K8SPS-305) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-305
---
**Problem:**
*Pause doesn't work for group-replication cluster with haproxy enabled.*
**Cause:**
*The function `pauseCluster` did not consider enabling haproxy for group-replication cluster and failed to find router deployment.*
**Solution:**
*Fix `pauseCluster` function. Add `gr-demand-backup-haproxy` test*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-305: fix pause for gr cluster with haproxy

go.mod, go.sum, pkg/controller/ps/status.go, pkg/controller/psbackup/controller.go, pkg/controller/psrestore/controller.go
[![K8SPS-309](https://badgen.net/badge/JIRA/K8SPS-309/green)](https://jira.percona.com/browse/K8SPS-309) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-309
---
**Problem:**
*On rare occasions, the cluster doesn't restart after being restored.*
**Cause:**
*Sometimes, the operator fails to update the status of `PerconaServerMySQLRestore` even if there is no error. When the operator fails to update to the `Succeeded` state, it will pause the cluster on the next `Reconcile` call. This can cause the cluster to get stuck in a loop where …
=> K8SPS-309: restore doesn't restart cluster

cmd/bootstrap/async_replication.go, pkg/replicator/replicator.go, pkg/replicator/replicatorexec.go
[![K8SPS-232](https://badgen.net/badge/JIRA/K8SPS-232/green)](https://jira.percona.com/browse/K8SPS-232) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Clone fails because of `super_read_only`.
**Solution:**
Disable `super_read_only` before clone.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPS-232: Fix restore in async cluster

api/v1alpha1/perconaservermysql_types.go
[![K8SPS-173](https://badgen.net/badge/JIRA/K8SPS-173/green)](https://jira.percona.com/browse/K8SPS-173) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Resetting a component size to the minimum size allowed when `allowUnsafeConfig` is not set is invisible to the user and can lead to confusion. 
**Solution:**
Log setting safe size if the unsafe config is not allowed
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-173]: https://perconadev.atlassian.net/browse/K8SPS-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> K8SPS-173: K8SPS-173: Log setting safe size if the unsafe config is not allowed

.github/pull_request_template.md, .github/workflows/reviewdog.yml, config/crd/bases/ps.percona.com_perconaservermysqlbackups.yaml, config/crd/bases/ps.percona.com_perconaservermysqlrestores.yaml, config/crd/bases/ps.percona.com_perconaservermysqls.yaml, deploy/bundle.yaml, deploy/crd.yaml
[![CLOUD-835](https://badgen.net/badge/JIRA/CLOUD-835/green)](https://jira.percona.com/browse/CLOUD-835) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We often forget updating manifests even though we have a checklist item in our pull requests. 
**Solution:**
We need to automate this check.
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-835]: https://perconadev.atlassian.net/browse/CLOUD-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLOUD-835: Add action to check if manifests are up-to-date 

README.md
[![CLOUD-820](https://badgen.net/badge/JIRA/CLOUD-820/green)](https://jira.percona.com/browse/CLOUD-820) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
modified:   README.md
---
**Problem:**
READMEs across all Operators are misaligned, having different structure, content and lacking links to Documentation
Update README to mention documentation
**Solution:**
Added Docs links, updated READMe structure and content
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-820]: …
=> CLOUD-820 Update README to mention documentation

e2e-tests/functions
---
**Problem:**
*Chaos mesh objects have finalizers and if you try to delete crd with these objects not yet deleted it might fail and cause next test to fail to re-initialize chaos mesh.*
**Solution:**
*Empty finalizer in chaos mesh objects before deleting the object and crd.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-314]: …
=> K8SPS-314 - Fix chaos mesh cleanup

Jenkinsfile
[![K8SPS-331](https://badgen.net/badge/JIRA/K8SPS-331/green)](https://jira.percona.com/browse/K8SPS-331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We have a community [PR](https://github.com/percona/percona-server-mysql-operator/pull/560) to migrate tests from `kuttl` to `chainsaw`, but the tests cannot run because community is not allowed to make changes in Jenkinsfile.*
**Solution:**
*Add chainsaw binary into our pipeline, until we evaluate it and eventually remove kuttl.*
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPS-331 - Add chainsaw binary into Jenkinsfile

pkg/xtrabackup/xtrabackup.go
---
**Problem:**
*Current backoffLimit of 10 seems to be too high for no apparent reason and the example in cr.yaml suggests that the default is 6*
**Solution:**
*For now make it the same as example in cr.yaml*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-314]: https://perconadev.atlassian.net/browse/K8SPS-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> K8SPS-314 - Lower backoffLimit from 10 to 6 as in cr.yaml example

config/manager/kustomization.yaml, config/manager/manager.yaml, deploy/bundle.yaml, deploy/operator.yaml
---
**Problem:**
*Operator upgrade fails because previous pod is not replaced with the new one.*
**Cause:**
*Missing upgrade strategy for operator deployment.*
**Solution:**
*Add upgrade strategy to operator deployment.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-314]: https://perconadev.atlassian.net/browse/K8SPS-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPS-314 - Add upgrade strategy to operator.yaml

.github/workflows/reviewdog.yml
[![CLOUD-849](https://badgen.net/badge/JIRA/CLOUD-849/green)](https://jira.percona.com/browse/CLOUD-849) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
On release branches we don't use main images so the reviewdog for manifests is failing and we need to ignore it.
**Solution:**
If a branch is named `release-` then we will use the exact version and instead of `perconalab` use `percona` repository. The check will only be done for operator image and bundles, not for other images since we cannot know all the versions.
**CHECKLIST**
---
**Jira** …
=> CLOUD-849 - Fix reviewdog for manifests on release branches

Jenkinsfile, e2e-tests/conf/cmctl.yml
[![CLOUD-850](https://badgen.net/badge/JIRA/CLOUD-850/green)](https://jira.percona.com/browse/CLOUD-850) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Update kuttl framework version to 0.16.0 and fix download of cert manager cmctl tool.
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-850]: https://perconadev.atlassian.net/browse/CLOUD-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLOUD-850 - Update kuttl version to 0.16.0

api/v1alpha1/perconaservermysql_types.go, e2e-tests/tests/limits/01-assert.yaml, e2e-tests/tests/limits/03-assert.yaml, e2e-tests/tests/limits/05-assert.yaml
[![K8SPS-346](https://badgen.net/badge/JIRA/K8SPS-346/green)](https://jira.percona.com/browse/K8SPS-346) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Bootstrap process fails due to timeout if dataset is bigger than 100 GB.
**Cause:**
Clone takes more 5 minutes.
**Solution:**
Increase default timeout to 12 hours.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-346]: https://perconadev.atlassian.net/browse/K8SPS-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-346: Increase default bootstrap timeout to 12 hours

pkg/controller/ps/upgrade.go
[![K8SPS-307](https://badgen.net/badge/JIRA/K8SPS-307/green)](https://jira.percona.com/browse/K8SPS-307) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-307]: https://perconadev.atlassian.net/browse/K8SPS-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> K8SPS-307 Fix missprint

pkg/controller/ps/status.go
[![K8SPS-366](https://badgen.net/badge/JIRA/K8SPS-366/green)](https://jira.percona.com/browse/K8SPS-366) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
On cluster delete the operator panics since we reconcile the status in a defer when there is no CR because it is deleted.
**Solution:**
Reconcile status only on a non-nil CR.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-366]: https://perconadev.atlassian.net/browse/K8SPS-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-366: Reconcile status only on a non-nil CR

cmd/orc-handler/main.go, pkg/controller/ps/controller.go, pkg/controller/ps/crash_recovery.go, pkg/controller/ps/status.go, pkg/controller/psrestore/controller.go, pkg/k8s/utils.go
[![K8SPS-241](https://badgen.net/badge/JIRA/K8SPS-241/green)](https://jira.percona.com/browse/K8SPS-241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Getting pods, PVCs, and services was done without specifying a namespace, only with labels, so everything was collected, from every namespace.
**Solution:**
Get all of these objects from a CR namespace.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-241]: https://perconadev.atlassian.net/browse/K8SPS-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> K8SPS-241: Get K8S objects within a specific namespace

pkg/controller/ps/controller.go, pkg/controller/ps/status.go, pkg/orchestrator/client.go
[![K8SPS-373](https://badgen.net/badge/JIRA/K8SPS-373/green)](https://jira.percona.com/browse/K8SPS-373) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-373
---
**Problem:**
_When using async cluster with 1 mysql pod, the operator prints the following error messages in the log:_
`
ERROR failed to update status {"controller": "ps-controller" ... "error": "check if async is ready: 2024-07-02 13:30:38 ERROR Unable to determine cluster name. clusterHint=cluster1.psasync" ...
`
_and_
`
ERROR failed to update status {"controller": …
=> K8SPS-373: reduce error logs on 1 mysql pod deployment

api/v1alpha1/perconaservermysql_types.go, config/crd/bases/ps.percona.com_perconaservermysqls.yaml, deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml
[![K8SPS-350](https://badgen.net/badge/JIRA/K8SPS-350/green)](https://jira.percona.com/browse/K8SPS-350) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We had `SSLInternalSecretName` in our CR but is not used and we don't need it. This PR removes it.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-350]: https://perconadev.atlassian.net/browse/K8SPS-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-350: Remove SSLInternalSecretName option

README.md
[![K8SPS-324](https://badgen.net/badge/JIRA/K8SPS-324/green)](https://jira.percona.com/browse/K8SPS-324) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-324]: https://perconadev.atlassian.net/browse/K8SPS-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> K8SPS-324 Update HAProxy usage details in README

e2e-tests/tests/monitoring/03-rotate-pmm-token.yaml
[![K8SPS-393](https://badgen.net/badge/JIRA/K8SPS-393/green)](https://jira.percona.com/browse/K8SPS-393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-393]: https://perconadev.atlassian.net/browse/K8SPS-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> K8SPS 393 naming fixes, remove key references in comments and file names

Jenkinsfile, e2e-tests/functions
[![K8SPS-393](https://badgen.net/badge/JIRA/K8SPS-393/green)](https://jira.percona.com/browse/K8SPS-393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
With the image and tag misconfigured, they are ignored, and instead, we are always using by default the latest released version.
**Cause:**
**Solution:**
based on this: https://github.com/percona/percona-helm-charts/tree/main/charts/pmm#percona-monitoring-and-management-pmm-parameters
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPS-393 use image.tag and image.repository to configure pmm3 server on e2e tests

api/v1alpha1/perconaservermysql_types.go
[![K8SPS-392](https://badgen.net/badge/JIRA/K8SPS-392/green)](https://jira.percona.com/browse/K8SPS-392) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-392
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-392]: https://perconadev.atlassian.net/browse/K8SPS-392?atlOrigin=eyJpIjoiNWRkNTlj …
=> K8SPS-392: add validation for `BOOTSTRAP_READ_TIMEOUT` in reconciler

Jenkinsfile, deploy/cr.yaml
[![K8SPS-126](https://badgen.net/badge/JIRA/K8SPS-126/green)](https://jira.percona.com/browse/K8SPS-126) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We have added a code for automatic storage change via volume expansion but the option in CR is missing which is confusing.
**Cause:**
**Solution:**
This PR adds the enableVolumeExpansion option to CR, following previously made code changes
**CHECKLIST**
---
**Jira**
- [+ ] Is the Jira ticket created and referenced properly?
- [+ ] …
=> K8SPS-126 Added volumeExpansion option to CR

pkg/orchestrator/orchestrator.go
[![K8SPS-269](https://badgen.net/badge/JIRA/K8SPS-269/green)](https://jira.percona.com/browse/K8SPS-269) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
For the orchestrator we have a separate method that creates a ConfigMap, so we’ll need to update that as well. In this PR I’d also like to discuss whether it makes sense to merge the two methods into one.
I checked labels for haproxy, router and orchestrator. 
**Cause:**
**Solution:**
*Short explanation of the solution we are …
=> K8SPS-269 fix labels for orchestrator

cmd/sidecar/main.go, pkg/controller/psbackup/controller.go, pkg/mysql/mysql.go
[![K8SPS-400](https://badgen.net/badge/JIRA/K8SPS-400/green)](https://jira.percona.com/browse/K8SPS-400) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
This PR addresses two problems:
1. Xtrabackup sidecar attempts to restart SQL thread on failure even if cluster uses group replication.
2. Unnecessary error log during backups.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-400]: https://perconadev.atlassian.net/browse/K8SPS-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPS-400 and K8SPS-527 fixes

e2e-tests/functions, e2e-tests/tests/monitoring/03-rotate-pmm-token.yaml
[![K8SPS-393](https://badgen.net/badge/JIRA/K8SPS-393/green)](https://jira.percona.com/browse/K8SPS-393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
On the existing e2e test for PMM3, when we are rotating the token, we need to ensure that the instance statefulsets are updated properly so that new pods are rolled out. 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPS-393 check sts generation before and after rotating the pmm3 token

e2e-tests/tests/init-deploy/01-assert.yaml, pkg/k8s/utils.go
[![K8SPS-417](https://badgen.net/badge/JIRA/K8SPS-417/green)](https://jira.percona.com/browse/K8SPS-417) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
```
2025-09-12T20:53:23.164Z        ERROR   Reconciler error        {"controller": "ps-controller", "controllerGroup": "ps.percona.com", "controllerKind": "PerconaServerMySQL", "PerconaServerMySQL": {"name":"ps-cluster1","namespace":"test"}, "namespace": "test", "name": "ps-cluster1", "reconcileID": "81936cc6-35b3-4e00-987e-62fd5aa486ba", "error": "reconcile: database: ensure component: failed to create pdb: …
```
=> K8SPS-417: Fix owner of PDB
