percona/percona-server-mysql-operator

- controllers/perconaservermysql_controller.go
The operator restarts replication if the user changes replication
password. If semi-sync replication enabled, the primary is locked due to
semi-sync wait count and orchestrator performs an automatic failover.
With this commit we're disabling semi-sync replication on primary before
restarting replication.
Another issue was making sure that replication is not running before
executing `CHANGE REPLICATION SOURCE TO ...`. It was sporadic but
frequent.
> K8SPS-65: Fix updating replication password with semi-sync replicas

- pkg/mysql/mysql.go
- pkg/orchestrator/orchestrator.go
Hello. This pull request adds the ability to deploy MySQL servers on dedicated nodes.
> Add tolerations and nodeselector

- pkg/mysql/mysql.go
https://jira.percona.com/browse/K8SPS-47
> K8SPS-47: Expose more mysql ports in services

- api/v1alpha1/perconaservermysql_types.go
- controllers/perconaservermysql_controller.go
- deploy/bundle.yaml
- deploy/crd.yaml
- pkg/mysql/mysql.go
- pkg/orchestrator/orchestrator.go
https://jira.percona.com/browse/K8SPS-72
Rename `serviceType` to `primaryServiceType`
Add `replicasServiceType` for headless service
Use `.expose.type` for per-pod services
> K8SPS-72: fix serviceTypes

- api/v1alpha1/perconaservermysql_types.go
https://jira.percona.com/browse/K8SPS-78
> K8SPS-78: operator should throw an error if `volumeSpec` is not specified

- e2e-tests/functions
- e2e-tests/tests/scaling/07-assert.yaml
> K8SPS-108 - Add --force-conflicts to deploy_operator

- api/v1alpha1/perconaservermysql_types.go
- config/crd/bases/ps.percona.com_perconaservermysqls.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
https://jira.percona.com/browse/K8SPS-103
> K8SPS-103: Add printer columns for orchestrator and router status

- api/v1alpha1/perconaservermysql_types.go
- config/crd/bases/ps.percona.com_perconaservermysqls.yaml
- controllers/perconaservermysqlbackup_controller.go
- deploy/bundle.yaml
- deploy/crd.yaml
- e2e-tests/tests/demand-backup/01-create-cluster.yaml
https://jira.percona.com/browse/K8SPS-88
> K8SPS-88: Support prefix field for cloud storages

- Jenkinsfile
- cmd/manager/main.go
- config/manager/manager.yaml
- deploy/bundle.yaml
- deploy/operator.yaml
- go.mod
- go.sum
Add support for configuring operator logging output through setting env vars:
`LOG_LEVEL: DEBUG/INFO/ERROR`
`LOG_STRUCTURED: true/false`
> K8SPS-98: Support log level and log formatting option

- e2e-tests/vars.sh
[![K8SPS-133](https://badgen.net/badge/JIRA/K8SPS-133/green)](https://jira.percona.com/browse/K8SPS-133) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-133 - Change E2E test images for backup and PS mysql

- controllers/perconaservermysql_controller.go
[![K8SPS-146](https://badgen.net/badge/JIRA/K8SPS-146/green)](https://jira.percona.com/browse/K8SPS-146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-146 Fix replication logs

- controllers/perconaservermysql_controller.go
[![K8SPS-125](https://badgen.net/badge/JIRA/K8SPS-125/green)](https://jira.percona.com/browse/K8SPS-125) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-125
> K8SPS-125: cluster secret shouldn't be removed during CR deletion

- deploy/secrets.yaml
[![K8SPS-17](https://badgen.net/badge/JIRA/K8SPS-17/green)](https://jira.percona.com/browse/K8SPS-17) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Without this the cluster startup from example files in deploy directory will fail.
> K8SPS-17 - Add heartbeat user into example secrets.yaml

- deploy/cr.yaml
- e2e-tests/functions
- e2e-tests/vars.sh
[![K8SPS-17](https://badgen.net/badge/JIRA/K8SPS-17/green)](https://jira.percona.com/browse/K8SPS-17) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-17 - Add parameter for choosing Toolkit image for the tests

- deploy/secrets.yaml
[![K8SPS-49](https://badgen.net/badge/JIRA/K8SPS-49/green)](https://jira.percona.com/browse/K8SPS-49) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-49 - Remove clustercheck user from deploy/secrets.yaml

- deploy/cr.yaml
[![K8SPS-63](https://badgen.net/badge/JIRA/K8SPS-63/green)](https://jira.percona.com/browse/K8SPS-63) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We disabled it by default in cr.yaml for other operators as well.
> K8SPS-63 - Disable automatic upgrade with VS in cr.yaml

- controllers/perconaservermysql_controller.go
[![K8SPS-146](https://badgen.net/badge/JIRA/K8SPS-146/green)](https://jira.percona.com/browse/K8SPS-146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-146: Fix semi-sync logs

- deploy/cr.yaml
> K8SPS-119 - Add initImage option to cr.yaml

- deploy/cr.yaml
> K8SPS-171 - Remove upgradeOptions since we don't support it in 0.3.0

- deploy/cr.yaml
> K8SPS-171 - Add initImage top level example in cr.yaml

- deploy/cr.yaml
> K8SPS-171 - Fix the haproxy image in cr.yaml

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- e2e-tests/functions
- e2e-tests/vars.sh
> K8SPS-171 - Release 0.3.0

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
> K8SPS-171 - Update after 0.3.0 release

- build/run-backup.sh
- controllers/perconaservermysqlbackup_controller.go
- pkg/xtrabackup/xtrabackup.go
[![K8SPS-187](https://badgen.net/badge/JIRA/K8SPS-187/green)](https://jira.percona.com/browse/K8SPS-187) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-187
> K8SPS-187: allow running only one backup at the same time

- Jenkinsfile
[![CLOUD-705](https://badgen.net/badge/JIRA/CLOUD-705/green)](https://jira.percona.com/browse/CLOUD-705) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
> CLOUD-705 add labels under cluster creation

- deploy/cr.yaml
- pkg/version/version.go
[![K8SPS-188](https://badgen.net/badge/JIRA/K8SPS-188/green)](https://jira.percona.com/browse/K8SPS-188) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-188 - Update versions for 0.4.0

- Jenkinsfile
- e2e-tests/functions
- e2e-tests/tests/haproxy/00-assert.yaml
- e2e-tests/tests/haproxy/00-deploy-operator.yaml
- e2e-tests/tests/haproxy/01-assert.yaml
- e2e-tests/tests/haproxy/01-create-cluster.yaml
- e2e-tests/tests/haproxy/02-write-data.yaml
- e2e-tests/tests/haproxy/03-assert.yaml
- e2e-tests/tests/haproxy/03-read-from-primary.yaml
- e2e-tests/tests/haproxy/04-assert.yaml
- e2e-tests/tests/haproxy/04-read-from-replicas.yaml
- e2e-tests/tests/haproxy/05-check-pods-have-same-primary.yaml
- e2e-tests/tests/haproxy/06-check-label-haproxy-primary.yaml
- e2e-tests/tests/haproxy/07-check-primary-failover.yaml
- e2e-tests/tests/haproxy/08-assert.yaml
- e2e-tests/tests/haproxy/08-disable-haproxy.yaml
- e2e-tests/tests/haproxy/09-errors.yaml
[![K8SPS-73](https://badgen.net/badge/JIRA/K8SPS-73/green)](https://jira.percona.com/browse/K8SPS-73) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-73 - Add haproxy test

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
[![K8SPS-188](https://badgen.net/badge/JIRA/K8SPS-188/green)](https://jira.percona.com/browse/K8SPS-188) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-188 - Versions update for release 0.4.0

- controllers/perconaservermysql_controller.go
[![K8SPS-179](https://badgen.net/badge/JIRA/K8SPS-179/green)](https://jira.percona.com/browse/K8SPS-179) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-179: Don't try to reconcile GR if cluster is paused

- cmd/bootstrap/async_replication.go
- pkg/replicator/replicator.go
[![K8SPS-202](https://badgen.net/badge/JIRA/K8SPS-202/green)](https://jira.percona.com/browse/K8SPS-202) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-202: Fix broken topology after restore

- build/Dockerfile
[![K8SPS-229](https://badgen.net/badge/JIRA/K8SPS-229/green)](https://jira.percona.com/browse/K8SPS-229) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-229 update base image to ubi9

- .github/pull_request_template.md
[![CLOUD-748](https://badgen.net/badge/JIRA/CLOUD-748/green)](https://jira.percona.com/browse/CLOUD-748) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> CLOUD-748 - Add checklist for Github PRs

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
[![K8SPS-188](https://badgen.net/badge/JIRA/K8SPS-188/green)](https://jira.percona.com/browse/K8SPS-188) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Description:**
*Update main branch after 0.4.0 release.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-188 - Update after 0.4.0 release

- Jenkinsfile
- e2e-tests/functions
- e2e-tests/tests/demand-backup/01-assert.yaml
- e2e-tests/tests/demand-backup/01-create-cluster.yaml
- e2e-tests/tests/demand-backup/05-assert.yaml
- e2e-tests/tests/demand-backup/08-assert.yaml
- e2e-tests/tests/demand-backup/12-assert.yaml
- e2e-tests/tests/demand-backup/16-assert.yaml
- e2e-tests/tests/demand-backup/20-assert.yaml
- e2e-tests/tests/gr-demand-backup/05-assert.yaml
- e2e-tests/tests/gr-demand-backup/09-assert.yaml
- e2e-tests/tests/gr-demand-backup/13-assert.yaml
- e2e-tests/tests/gr-demand-backup/17-assert.yaml
- e2e-tests/tests/init-deploy/01-assert.yaml
- e2e-tests/tests/init-deploy/01-create-cluster.yaml
- e2e-tests/tests/one-pod/01-assert.yaml
- e2e-tests/tests/one-pod/01-create-cluster.yaml
- e2e-tests/tests/scaling/01-create-cluster.yaml
- e2e-tests/tests/scaling/06-scale-up.yaml
- e2e-tests/tests/scaling/08-assert.yaml
- e2e-tests/tests/scaling/08-scale-down.yaml
- e2e-tests/tests/users/01-assert.yaml
- e2e-tests/tests/users/01-create-cluster.yaml
- e2e-tests/tests/users/04-assert.yaml
- e2e-tests/tests/users/04-check-cluster.yaml
- e2e-tests/vars.sh
[![K8SPS-237](https://badgen.net/badge/JIRA/K8SPS-237/green)](https://jira.percona.com/browse/K8SPS-237) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Tests currently cannot run on MiniKube because of number of reasons.*
**Cause:**
*Resources, LoadBalancer, affinity etc.*
**Solution:**
*Set affinity to `none` just on MiniKube. Lower resources for haproxy pods, fix waiting for cluster consistency, fix timeouts.
Corresponding PR for pipelines is located here: https://github.com/Percona-Lab/jenkins-pipelines/pull/1956*
**CHECKLIST**
---
**Jira** …
> K8SPS-237 - Fix running tests on minikube

- README.md
[![K8SPS-252](https://badgen.net/badge/JIRA/K8SPS-252/green)](https://jira.percona.com/browse/K8SPS-252) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-252 Add shields to README

- deploy/cr.yaml
- pkg/version/version.go
---
**Problem:**
*Seems we forgot to bump it after previous release...*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 - Bump version from 0.4.0 to 0.5.0

- e2e-tests/tests/demand-backup/04-move-primary-before-backup.yaml
[![K8SPS-73](https://badgen.net/badge/JIRA/K8SPS-73/green)](https://jira.percona.com/browse/K8SPS-73) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-73 - Minor update to demand-backup test

- deploy/cr.yaml
[![K8SPS-73](https://badgen.net/badge/JIRA/K8SPS-73/green)](https://jira.percona.com/browse/K8SPS-73) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
*Adding missing options for upgrade and router custom configuration.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-73 - Add upgrade and router configuration opts to cr.yaml

- e2e-tests/functions
- pkg/controller/ps/testdata/cert-manager.yaml
---
**Problem:**
We need to update cer-manager in tests. 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 update cert-manager version

- config/crd/bases/ps.percona.com_perconaservermysqls.yaml
- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/operator.yaml
---
*This updates the manifests and versions for 0.5.0 release*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 - Update manifests and versions for 0.5.0 release

- deploy/cr.yaml
---
*Use official images for haproxy, router and orchestrator from 0.5.0 release.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 - Update images for haproxy, router and orchestrator

- e2e-tests/tests/async-ignore-annotations/02-assert.yaml
- e2e-tests/tests/gr-ignore-annotations/02-assert.yaml
---
**Problem:**
Fix tests for eks
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 update tests for eks

- e2e-tests/functions
---
*In a resource constrained environment tests run better on minikube with this included.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8S238 - Minikube tests - lower haproxy cpu requests

- config/crd/bases/ps.percona.com_perconaservermysqls.yaml
- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/operator.yaml
- e2e-tests/functions
- e2e-tests/tests/async-ignore-annotations/02-assert.yaml
- e2e-tests/tests/gr-ignore-annotations/02-assert.yaml
- pkg/controller/ps/version.go
---
*Release branch for 0.5.0*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 - Release 0.5.0

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- pkg/version/version.go
---
*This updates version after 0.5.0 release.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-238 - Update versions after 0.5.0 release

- pkg/controller/psbackup/controller_test.go
[![K8SPS-257](https://badgen.net/badge/JIRA/K8SPS-257/green)](https://jira.percona.com/browse/K8SPS-257) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPS-257
---
**Problem:**
*`TestCheckFinalizers` unit-test was broken.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-257: fix `TestCheckFinalizers` unit-test

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-727 add day and time for dependabot

- build/haproxy-global.cfg
- build/haproxy.cfg
- build/haproxy_add_mysql_nodes.sh
- e2e-tests/conf/client.yaml
- e2e-tests/functions
- e2e-tests/tests/gr-haproxy/03-check-connections.yaml
[![K8SPS-162](https://badgen.net/badge/JIRA/K8SPS-162/green)](https://jira.percona.com/browse/K8SPS-162) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Ports for x protocol and admin port were not properly set in haproxy config so they could not be used this way.*
**Solution:**
*Add these backends and link frontends properly to x protocol and admin backends in haproxy.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-162 - Fix mysql x protocol from haproxy

- deploy/cr.yaml
[![K8SPS-300](https://badgen.net/badge/JIRA/K8SPS-300/green)](https://jira.percona.com/browse/K8SPS-300) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPS-300 change default value for service annotation

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
[![K8SPS-313](https://badgen.net/badge/JIRA/K8SPS-313/green)](https://jira.percona.com/browse/K8SPS-313) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**This is image update for 0.6.0 release**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-267 - Update images and versions for 0.6.0 release

- cmd/bootstrap/async_replication.go
- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- e2e-tests/functions
- e2e-tests/tests/gr-self-healing/01-assert.yaml
- e2e-tests/tests/gr-self-healing/05-assert.yaml
- e2e-tests/tests/gr-self-healing/08-assert.yaml
- e2e-tests/tests/gr-self-healing/11-assert.yaml
- e2e-tests/tests/monitoring/02-assert.yaml
- e2e-tests/tests/monitoring/03-assert.yaml
- e2e-tests/tests/operator-self-healing/01-assert.yaml
- pkg/replicator/replicator.go
- pkg/replicator/replicatorexec.go
[![K8SPS-267](https://badgen.net/badge/JIRA/K8SPS-267/green)](https://jira.percona.com/browse/K8SPS-267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*This is a release branch for 0.6.0 release*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-267 - Release 0.6.0

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- pkg/version/version.go
[![K8SPS-267](https://badgen.net/badge/JIRA/K8SPS-267/green)](https://jira.percona.com/browse/K8SPS-267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Update main images and versions after 0.6.0 release*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-267 - Update main images and versions after 0.6.0 release

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-727 set day and time for all packages

- e2e-tests/functions
[![CLOUD-789](https://badgen.net/badge/JIRA/CLOUD-789/green)](https://jira.percona.com/browse/CLOUD-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-789-2 - splitting local variable declaration from assingning value for best practices

- .github/CODEOWNERS
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Prune codeowners for github

- Jenkinsfile
[![CLOUD-814](https://badgen.net/badge/JIRA/CLOUD-814/green)](https://jira.percona.com/browse/CLOUD-814) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> Move from Kubernetes Platfrom v 1.14 to v 1.25 for all operator test cases

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* we can set day only for weekly interval
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CLOUD-727 update schedule section for gomod

- e2e-tests/tests/one-pod/02-write-data.yaml
- e2e-tests/tests/one-pod/05-assert.yaml
- e2e-tests/tests/one-pod/06-assert.yaml
- e2e-tests/tests/one-pod/06-read-data.yaml
[![K8SPS-73](https://badgen.net/badge/JIRA/K8SPS-73/green)](https://jira.percona.com/browse/K8SPS-73) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-73]: https://perconadev.atlassian.net/browse/K8SPS-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
> K8SPS-73 make one-pod test stable

- e2e-tests/tests/limits/01-assert.yaml
- e2e-tests/tests/limits/03-assert.yaml
- e2e-tests/tests/limits/05-assert.yaml
- pkg/orchestrator/orchestrator.go
[![K8SPS-329](https://badgen.net/badge/JIRA/K8SPS-329/green)](https://jira.percona.com/browse/K8SPS-329) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-329]: https://perconadev.atlassian.net/browse/K8SPS-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-329 use peer-list from init image

- Jenkinsfile
- e2e-tests/functions
- e2e-tests/tests/version-service/00-deploy-operator.yaml
- e2e-tests/tests/version-service/01-assert.yaml
[![K8SPS-328](https://badgen.net/badge/JIRA/K8SPS-328/green)](https://jira.percona.com/browse/K8SPS-328) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-328]: https://perconadev.atlassian.net/browse/K8SPS-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-328 fix version-service test

- .github/workflows/scan.yml
- Jenkinsfile
- build/Dockerfile
- e2e-tests/build
- e2e-tests/functions
[![K8SPS-332](https://badgen.net/badge/JIRA/K8SPS-332/green)](https://jira.percona.com/browse/K8SPS-332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-332]: https://perconadev.atlassian.net/browse/K8SPS-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-332 add multi architecture build support

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-314]: https://perconadev.atlassian.net/browse/K8SPS-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-314 Update images and versions for 0.7.0 release

- e2e-tests/functions
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Update cert-manager version to v1.14.4

- e2e-tests/tests/gr-demand-backup/02-assert.yaml
- e2e-tests/tests/gr-tls-cert-manager/02-assert.yaml
- e2e-tests/tests/gr-tls-cert-manager/06-assert.yaml
- e2e-tests/tests/tls-cert-manager/02-assert.yaml
- e2e-tests/tests/tls-cert-manager/04-assert.yaml
- e2e-tests/tests/tls-cert-manager/06-assert.yaml
[![K8SPS-182](https://badgen.net/badge/JIRA/K8SPS-182/green)](https://jira.percona.com/browse/K8SPS-182) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We're not checking cluster status properly, we just check certificates.*
**Solution:**
*Add checking of cluster status.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-182]: https://perconadev.atlassian.net/browse/K8SPS-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPS-182 - Improve checks in tls-cert-manager tests

- e2e-tests/README.md
[![K8SPS-129](https://badgen.net/badge/JIRA/K8SPS-129/green)](https://jira.percona.com/browse/K8SPS-129) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Add readme about building and testing the Operator.*
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-129]: https://perconadev.atlassian.net/browse/K8SPS-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> K8SPS-129 add e2e tests readme

- config/manager/kustomization.yaml
- config/manager/manager.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- e2e-tests/functions
- e2e-tests/tests/gr-demand-backup/02-assert.yaml
- e2e-tests/tests/gr-tls-cert-manager/02-assert.yaml
- e2e-tests/tests/gr-tls-cert-manager/06-assert.yaml
- e2e-tests/tests/tls-cert-manager/02-assert.yaml
- e2e-tests/tests/tls-cert-manager/04-assert.yaml
- e2e-tests/tests/tls-cert-manager/06-assert.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-314 - Release 0.7.0

- config/manager/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
- pkg/version/version.go
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-314]: https://perconadev.atlassian.net/browse/K8SPS-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-314 Update image tags back to main (related to 0.7.0 release)

- Makefile
- deploy/cr.yaml
- e2e-tests/functions
- e2e-tests/vars.sh
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Manual steps need to be taken to prepare release branch and also to prepare main branch after release branch is merged.*
**Solution:**
With this manifests will be prepared but also next version and main images set in cr.yaml. What we need to still do manually is set specific database/backup and other images before the release since each product has it's own.
Prepare release example:
`make release …
> CLOUD-833 - Add release and after-release Makefile targets

- Makefile
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-833]: https://perconadev.atlassian.net/browse/CLOUD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-833 - Cleanup in release and after-release Makefile targets

- Makefile
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-833]: https://perconadev.atlassian.net/browse/CLOUD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-833 - Minor update for release and after-release Makefile targets

- Jenkinsfile
- build/Dockerfile
- e2e-tests/build
[![K8SPS-301](https://badgen.net/badge/JIRA/K8SPS-301/green)](https://jira.percona.com/browse/K8SPS-301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* Golang builds faster in native architecture.
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-301]: https://perconadev.atlassian.net/browse/K8SPS-301?atlOrigin=eyJpIjoiNWRkNTljNzY …
> K8SPS-301 improve multi arch builds

- deploy/cr.yaml
[![K8SPS-345](https://badgen.net/badge/JIRA/K8SPS-345/green)](https://jira.percona.com/browse/K8SPS-345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-345]: https://perconadev.atlassian.net/browse/K8SPS-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-345 add annotation to CR

- Jenkinsfile
[![CLOUD-850](https://badgen.net/badge/JIRA/CLOUD-850/green)](https://jira.percona.com/browse/CLOUD-850) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-850]: https://perconadev.atlassian.net/browse/CLOUD-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-850 - Update kuttl version to v0.17.0

- config/rbac/role.yaml
- deploy/bundle.yaml
- deploy/rbac.yaml
- pkg/controller/ps/controller.go
[![K8SPS-241](https://badgen.net/badge/JIRA/K8SPS-241/green)](https://jira.percona.com/browse/K8SPS-241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Generated rbac for single-namespace had wrong apigroup for role/rolebinding rules.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-241]: https://perconadev.atlassian.net/browse/K8SPS-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPS-241: Correct apigroup for role/rolebingins

- e2e-tests/functions
- e2e-tests/tests/gr-finalizer/99-remove-cluster-gracefully.yaml
- e2e-tests/tests/gr-tls-cert-manager/99-remove-cluster-gracefully.yaml
- e2e-tests/tests/tls-cert-manager/99-remove-cluster-gracefully.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPS-328 destroy cert-manager

- config/manager/cluster/kustomization.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- e2e-tests/vars.sh
[![K8SPS-343](https://badgen.net/badge/JIRA/K8SPS-343/green)](https://jira.percona.com/browse/K8SPS-343) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-343]: https://perconadev.atlassian.net/browse/K8SPS-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-343 Update images and versions for 0.8.0 release

- e2e-tests/tests/gr-security-context/04-assert.yaml
- e2e-tests/tests/gr-security-context/07-assert.yaml
[![K8SPS-340](https://badgen.net/badge/JIRA/K8SPS-340/green)](https://jira.percona.com/browse/K8SPS-340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-340
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-340]: https://perconadev.atlassian.net/browse/K8SPS-340?atlOrigin=eyJpIjoiNWRkNTlj …
> K8SPS-340: fix `gr-security-context` test

- Jenkinsfile
- config/manager/cluster/kustomization.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- pkg/version/version.go
[![K8SPS-343](https://badgen.net/badge/JIRA/K8SPS-343/green)](https://jira.percona.com/browse/K8SPS-343) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-343]: https://perconadev.atlassian.net/browse/K8SPS-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-343 Update image tags back to main (related to 0.8.0 release)

- cmd/bootstrap/async_replication.go
[![K8SPS-372](https://badgen.net/badge/JIRA/K8SPS-372/green)](https://jira.percona.com/browse/K8SPS-372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-372
---
**Problem:**
*When a cluster with `mysqlSize: 2` is updated to trigger the mysql statefulset update, the first pod gets stuck in `CrashLoopBackOff`.*
**Cause:**
_Initial topology of the 2 MySQL pod deployment:_
- _First pod is primary_
- _Second pod is replica._
_During the smart update, the second pod successfully performs the update and then the process moves to the …
> K8SPS-372: fix bootstrap for cluster with 2 mysql pods

- README.md
[![CLOUD-878](https://badgen.net/badge/JIRA/CLOUD-878/green)](https://jira.percona.com/browse/CLOUD-878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
adding some links and minor fixes into readme
[CLOUD-878]: https://perconadev.atlassian.net/browse/CLOUD-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLOUD-878] fixing readme with some links

- config/manager/cluster/kustomization.yaml
- config/manager/cluster/manager.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- pkg/version/version.go
[![K8SPS-376](https://badgen.net/badge/JIRA/K8SPS-376/green)](https://jira.percona.com/browse/K8SPS-376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Post-release step: New version code preparations in main branch
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-376]: https://perconadev.atlassian.net/browse/K8SPS-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPS-376 Update image tags back to main (related to 0.9.0 release)

- Jenkinsfile
[![K8SPS-424](https://badgen.net/badge/JIRA/K8SPS-424/green)](https://jira.percona.com/browse/K8SPS-424) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-424]: https://perconadev.atlassian.net/browse/K8SPS-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-424 Jenkinsfile cluster-version set to 1.29 from 1.28

- e2e-tests/tests/demand-backup/06-check-password-leak.yaml
- e2e-tests/tests/demand-backup/09-check-password-leak.yaml
- e2e-tests/tests/gr-haproxy/04-check-password-leak.yaml
- e2e-tests/tests/gr-init-deploy/06-check-password-leak.yaml
- e2e-tests/tests/haproxy/08-check-password-leak.yaml
- e2e-tests/tests/init-deploy/07-check-password-leak.yaml
- e2e-tests/tests/monitoring/05-check-password-leak.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Disable pass check in tests

- pkg/controller/ps/controller.go
[![K8SPS-374](https://badgen.net/badge/JIRA/K8SPS-374/green)](https://jira.percona.com/browse/K8SPS-374) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPS-374
---
This PR prevents the operator from logging `Orchestrator add peers` and `Orchestrator remove peers` errors when the cluster is paused
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-374]: https://perconadev.atlassian.net/browse/K8SPS-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPS-374: ignore reconcileOrchestrator errors on pause

- .github/workflows/reviewdog.yml
[![K8SPS-371](https://badgen.net/badge/JIRA/K8SPS-371/green)](https://jira.percona.com/browse/K8SPS-371) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPS-371]: https://perconadev.atlassian.net/browse/K8SPS-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPS-371 fix reviewdog
